#!/bin/bash
# 科学计算器 APK 打包脚本

echo "=== 科学计算器 APK 打包 ==="
echo ""
echo "注意：Buildozer 需要在 Linux 环境运行"
echo "Android/Termux 不支持直接打包"
echo ""
echo "推荐打包方式："
echo ""
echo "方式1: 使用 GitHub Actions (免费)"
echo "  1. 上传 calculator_kivy 文件夹到 GitHub 仓库"
echo "  2. 创建 .github/workflows/build.yml"
echo "  3. GitHub 自动编译生成 APK"
echo ""
echo "方式2: 使用本地 Linux 电脑"
echo "  pip install buildozer"
echo "  cd calculator_kivy"
echo "  buildozer android debug"
echo ""
echo "方式3: 使用 Docker"
echo "  docker pull kivy/buildozer"
echo "  docker run -v $(pwd):/app kivy/buildozer android debug"
echo ""
